[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Environment variables for production
# Set these in your Netlify dashboard under Site settings > Environment variables
[context.production.environment]
  # CONTACT_FORM_WEBHOOK_URL = "your-contact-webhook-url-here"
  # NEWSLETTER_WEBHOOK_URL = "your-newsletter-webhook-url-here"
  # CHATBOT_WEBHOOK_URL = "your-chatbot-webhook-url-here"

# Environment variables for deploy previews
[context.deploy-preview.environment]
  # CONTACT_FORM_WEBHOOK_URL = "your-staging-contact-webhook-url-here"
  # NEWSLETTER_WEBHOOK_URL = "your-staging-newsletter-webhook-url-here"
  # CHATBOT_WEBHOOK_URL = "your-staging-chatbot-webhook-url-here"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  # CONTACT_FORM_WEBHOOK_URL = "your-staging-contact-webhook-url-here"
  # NEWSLETTER_WEBHOOK_URL = "your-staging-newsletter-webhook-url-here"
  # CHATBOT_WEBHOOK_URL = "your-staging-chatbot-webhook-url-here"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect for SPA (if needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Security headers for forms
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"